version: '3.8'
services:
  surveyor:
    container_name: surveyor
    build: .
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    ports:
      - "8080:8080"
    environment:
      - TZ=America/New_York
    restart: unless-stopped

    # Uncomment to run surveyor with custom arguments
    # command: ["/app/surveyor", "--addr", ":80"]
